import { Client, Assessment, Interview, Report, Task, Appointment, ASSESSMENT_TYPES } from '../types';

export const mockClients: Client[] = [
  {
    id: 'c1',
    name: '张明',
    gender: 'male',
    age: 28,
    phone: '13812345678',
    email: 'zhangming@example.com',
    occupation: '软件工程师',
    education: '本科',
    consultationBackground: '工作3年后感觉职业发展遇到瓶颈，想要探索新的职业方向',
    currentStage: 'interview',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ZhangMing',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
  },
  {
    id: 'c2',
    name: '李雪',
    gender: 'female',
    age: 25,
    phone: '13923456789',
    email: 'lixue@example.com',
    occupation: '市场专员',
    education: '硕士',
    consultationBackground: '刚毕业不久，对未来职业方向感到迷茫',
    currentStage: 'assessment',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LiXue',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-22',
  },
  {
    id: 'c3',
    name: '王建国',
    gender: 'male',
    age: 35,
    phone: '13734567890',
    email: 'wangjianguo@example.com',
    occupation: '产品经理',
    education: '本科',
    consultationBackground: '在现有公司工作5年，考虑是否应该转型或创业',
    currentStage: 'report_writing',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=WangJianguo',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-25',
  },
  {
    id: 'c4',
    name: '陈思琪',
    gender: 'female',
    age: 30,
    phone: '13645678901',
    email: 'chensiqi@example.com',
    occupation: '设计师',
    education: '硕士',
    consultationBackground: '希望从传统设计转向互联网产品设计',
    currentStage: 'follow_up',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ChenSiqi',
    createdAt: '2024-01-05',
    updatedAt: '2024-01-28',
  },
  {
    id: 'c5',
    name: '刘洋',
    gender: 'male',
    age: 26,
    phone: '13556789012',
    email: 'liuyang@example.com',
    occupation: '财务分析师',
    education: '本科',
    consultationBackground: '对当前工作不感兴趣，想探索其他可能性',
    currentStage: 'initial_assessment',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LiuYang',
    createdAt: '2024-01-28',
    updatedAt: '2024-01-28',
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: 'a1',
    clientId: 'c1',
    assessmentType: ASSESSMENT_TYPES[0],
    sentAt: '2024-01-16',
    completedAt: '2024-01-17',
    status: 'completed',
    result: {
      id: 'ar1',
      assessmentId: 'a1',
      scores: [
        { dimension: '现实型(R)', score: 45 },
        { dimension: '研究型(I)', score: 72 },
        { dimension: '艺术型(A)', score: 58 },
        { dimension: '社会型(S)', score: 62 },
        { dimension: '企业型(E)', score: 40 },
        { dimension: '常规型(C)', score: 55 },
      ],
      interpretation: '研究型和社会型得分较高，适合从事需要分析能力和人际交往的职业',
      createdAt: '2024-01-17',
    },
  },
  {
    id: 'a2',
    clientId: 'c1',
    assessmentType: ASSESSMENT_TYPES[1],
    sentAt: '2024-01-18',
    completedAt: '2024-01-19',
    status: 'completed',
    result: {
      id: 'ar2',
      assessmentId: 'a2',
      scores: [
        { dimension: '外向-内向', score: 55 },
        { dimension: '感觉-直觉', score: 68 },
        { dimension: '思考-情感', score: 48 },
        { dimension: '判断-知觉', score: 62 },
      ],
      interpretation: 'INTJ型，独立思考者，善于分析和规划',
      createdAt: '2024-01-19',
    },
  },
  {
    id: 'a3',
    clientId: 'c2',
    assessmentType: ASSESSMENT_TYPES[0],
    sentAt: '2024-01-19',
    completedAt: '2024-01-20',
    status: 'completed',
    result: {
      id: 'ar3',
      assessmentId: 'a3',
      scores: [
        { dimension: '现实型(R)', score: 35 },
        { dimension: '研究型(I)', score: 48 },
        { dimension: '艺术型(A)', score: 75 },
        { dimension: '社会型(S)', score: 80 },
        { dimension: '企业型(E)', score: 55 },
        { dimension: '常规型(C)', score: 42 },
      ],
      interpretation: '社会型和艺术型得分较高，适合创意性工作',
      createdAt: '2024-01-20',
    },
  },
  {
    id: 'a4',
    clientId: 'c2',
    assessmentType: ASSESSMENT_TYPES[2],
    sentAt: '2024-01-21',
    status: 'pending',
  },
  {
    id: 'a5',
    clientId: 'c3',
    assessmentType: ASSESSMENT_TYPES[0],
    sentAt: '2024-01-12',
    completedAt: '2024-01-13',
    status: 'completed',
    result: {
      id: 'ar5',
      assessmentId: 'a5',
      scores: [
        { dimension: '现实型(R)', score: 50 },
        { dimension: '研究型(I)', score: 55 },
        { dimension: '艺术型(A)', score: 40 },
        { dimension: '社会型(S)', score: 65 },
        { dimension: '企业型(E)', score: 78 },
        { dimension: '常规型(C)', score: 60 },
      ],
      interpretation: '企业型得分最高，适合管理和领导类岗位',
      createdAt: '2024-01-13',
    },
  },
  {
    id: 'a6',
    clientId: 'c4',
    assessmentType: ASSESSMENT_TYPES[3],
    sentAt: '2024-01-08',
    completedAt: '2024-01-10',
    status: 'completed',
    result: {
      id: 'ar6',
      assessmentId: 'a6',
      scores: [
        { dimension: '沟通能力', score: 85 },
        { dimension: '领导力', score: 70 },
        { dimension: '分析能力', score: 75 },
        { dimension: '创新能力', score: 88 },
        { dimension: '执行能力', score: 78 },
        { dimension: '团队协作', score: 82 },
      ],
      interpretation: '创新能力和沟通能力突出，适合创意类和管理类岗位',
      createdAt: '2024-01-10',
    },
  },
];

export const mockInterviews: Interview[] = [
  {
    id: 'i1',
    clientId: 'c1',
    interviewDate: '2024-01-20',
    duration: 60,
    summary: '来访者工作3年，主要困惑是技术深度与广度的平衡问题。他希望在保持技术竞争力的同时，向管理层方向发展。',
    confusionTypes: ['career_positioning', 'development_bottleneck'],
    strengths: ['逻辑思维能力强', '技术基础扎实', '学习能力出色', '沟通表达清晰'],
    limitations: ['过于追求完美', '时间管理有待提升', '对管理工作的了解不足'],
    nextSteps: '继续完成剩余测评，整理职业兴趣和能力画像',
    createdAt: '2024-01-20',
  },
  {
    id: 'i2',
    clientId: 'c2',
    interviewDate: '2024-01-22',
    duration: 45,
    summary: '来访者硕士毕业半年，在校期间有过多段实习经历但都较短暂。目前对职业方向仍感迷茫。',
    confusionTypes: ['career_positioning', 'career_transition'],
    strengths: ['学习能力强', '有艺术背景', '善于观察和体验'],
    limitations: ['缺乏明确方向', '实践经验不足', '自信度有待提升'],
    nextSteps: '完成职业价值观测评，明确核心职业诉求',
    createdAt: '2024-01-22',
  },
  {
    id: 'i3',
    clientId: 'c3',
    interviewDate: '2024-01-25',
    duration: 90,
    summary: '来访者在当前公司发展遇到天花板，考虑创业或转型。家庭因素也是重要考量。',
    confusionTypes: ['career_transition', 'salary_expectation'],
    strengths: ['产品思维成熟', '资源整合能力强', '项目管理经验丰富', '抗压能力好'],
    limitations: ['过于保守', '风险偏好低', '创新意识不足'],
    nextSteps: '撰写综合诊断报告，分析创业可行性',
    createdAt: '2024-01-25',
  },
  {
    id: 'i4',
    clientId: 'c4',
    interviewDate: '2024-01-28',
    duration: 60,
    summary: '来访者已完成所有测评和访谈，正在执行探索任务。目前进展顺利，已完成2/3任务。',
    confusionTypes: ['career_transition'],
    strengths: ['设计能力强', '审美优秀', '用户洞察敏锐', '执行效率高'],
    limitations: ['技术深度有限', '商业思维薄弱'],
    nextSteps: '继续执行剩余探索任务，下次访谈评估转型准备度',
    createdAt: '2024-01-28',
  },
];

export const mockReports: Report[] = [
  {
    id: 'r1',
    clientId: 'c1',
    title: '张明职业发展诊断报告',
    content: `基于霍兰德职业兴趣测评、MBTI性格测试及访谈信息，综合分析如下：

## 职业兴趣分析
来访者在研究型和社会型维度得分较高，显示出对分析性问题解决的兴趣，以及与人协作的需求。

## 性格特点
INTJ类型，独立思考者，善于长远规划和系统分析。

## 发展建议
1. 技术专家路线：深耕技术领域，成为架构师或技术专家
2. 技术管理路线：适当拓展管理技能，向技术经理方向发展
3. 产品方向转型：利用技术背景，转型产品经理

## 探索任务
1. 与3位不同职业方向的从业者进行职业访谈
2. 尝试主导一个跨部门项目
3. 阅读《非暴力沟通》并实践`,
    careerRecommendations: [
      {
        id: 'cr1',
        careerName: '技术架构师',
        matchScore: 85,
        reason: '充分发挥技术专长，同时有足够复杂度满足研究型需求',
        explorationTasks: ['学习系统设计', '参与架构评审', '阅读优秀开源项目'],
      },
      {
        id: 'cr2',
        careerName: '产品经理',
        matchScore: 75,
        reason: '利用技术背景进行产品决策，平衡分析和人际需求',
        explorationTasks: ['学习产品方法论', '完成产品项目', '提升商业思维'],
      },
      {
        id: 'cr3',
        careerName: '技术经理',
        matchScore: 70,
        reason: '兼顾技术深度和团队管理',
        explorationTasks: ['学习团队管理', '参与招聘面试', '练习技术方案汇报'],
      },
    ],
    status: 'sent',
    createdAt: '2024-01-21',
    updatedAt: '2024-01-23',
  },
  {
    id: 'r2',
    clientId: 'c3',
    title: '王建国职业发展诊断报告（草稿）',
    content: `报告撰写中...`,
    careerRecommendations: [],
    status: 'draft',
    createdAt: '2024-01-26',
    updatedAt: '2024-01-26',
  },
];

export const mockTasks: Task[] = [
  {
    id: 't1',
    clientId: 'c1',
    reportId: 'r1',
    title: '完成职业访谈',
    description: '与3位不同职业方向的从业者进行深度职业访谈',
    dueDate: '2024-02-15',
    status: 'in_progress',
    createdAt: '2024-01-23',
  },
  {
    id: 't2',
    clientId: 'c1',
    reportId: 'r1',
    title: '主导跨部门项目',
    description: '在当前公司寻找机会，主导一个需要跨部门协作的项目',
    dueDate: '2024-02-28',
    status: 'todo',
    createdAt: '2024-01-23',
  },
  {
    id: 't3',
    clientId: 'c1',
    reportId: 'r1',
    title: '阅读《非暴力沟通》',
    description: '阅读书籍并记录关键要点，尝试在实际工作中应用',
    dueDate: '2024-02-10',
    status: 'completed',
    createdAt: '2024-01-23',
  },
  {
    id: 't4',
    clientId: 'c4',
    title: '完成UI设计作品集',
    description: '整理并优化设计作品集，准备互联网产品设计方向求职',
    dueDate: '2024-02-20',
    status: 'in_progress',
    createdAt: '2024-01-29',
  },
  {
    id: 't5',
    clientId: 'c4',
    title: '学习Axure原型设计',
    description: '掌握Axure基础操作，能够制作交互原型',
    dueDate: '2024-02-15',
    status: 'completed',
    createdAt: '2024-01-29',
  },
  {
    id: 't6',
    clientId: 'c4',
    title: '参加产品设计培训',
    description: '报名参加线上产品设计课程，系统学习产品设计方法',
    dueDate: '2024-03-01',
    status: 'todo',
    createdAt: '2024-01-29',
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: 'ap1',
    clientId: 'c1',
    scheduledAt: '2024-02-05 10:00',
    duration: 60,
    method: 'offline',
    notes: '第二次咨询，评估职业访谈进展',
    status: 'scheduled',
  },
  {
    id: 'ap2',
    clientId: 'c2',
    scheduledAt: '2024-02-05 14:00',
    duration: 45,
    method: 'online',
    notes: '测评结果解读',
    status: 'scheduled',
  },
  {
    id: 'ap3',
    clientId: 'c3',
    scheduledAt: '2024-02-06 09:00',
    duration: 90,
    method: 'offline',
    notes: '报告终稿确认会议',
    status: 'scheduled',
  },
  {
    id: 'ap4',
    clientId: 'c4',
    scheduledAt: '2024-02-08 15:00',
    duration: 60,
    method: 'offline',
    notes: '转型准备度评估',
    status: 'scheduled',
  },
];
